# Generated by Django 4.0.2 on 2022-02-19 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=19, validators=[django.core.validators.RegexValidator(regex='^\\d{4}-\\d{4}-\\d{4}-\\d{4}$')])),
                ('last_login', models.DateTimeField()),
            ],
        ),
    ]
