# Generated by Django 4.0.2 on 2022-02-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='is_using',
            field=models.BooleanField(default=False),
        ),
    ]
