# Generated by Django 4.0.2 on 2022-02-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_token_is_using'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='last_login',
        ),
        migrations.AddField(
            model_name='token',
            name='last_join',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
