# Generated by Django 4.0.2 on 2022-02-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0004_alter_token_last_join'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='is_using',
        ),
        migrations.AddField(
            model_name='token',
            name='ip_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=19),
        ),
    ]
