# Generated by Django 4.0.2 on 2022-02-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0005_remove_token_is_using_token_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
