# Generated by Django 4.0.2 on 2022-03-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0007_alter_token_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='last_join',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
